# Generated by Django 4.2.2 on 2023-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_images_house_other_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='house',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
