# Generated by Django 4.2.2 on 2023-06-12 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_alter_images_options_house_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inspection_date', models.CharField(max_length=100)),
                ('inspection_time', models.CharField(max_length=100)),
                ('house_location', models.CharField(max_length=100)),
                ('property_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
